modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="hyperion"
version="1.0.0"
displayName="Hyperion"
description="Adds the Hyperion sword with Wither Impact ability."

[[dependencies.hyperion]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hyperion]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
